HW4
julianoh7/Summer2021_Selanium pull request #3
Opened 2021-09-26 23:36 UTC by julianoh7

2021-09-27 18:18 UTC, ahsansiddiki requested changes

2021-09-30 00:41 UTC, julianoh7 commented on src/test/java/SeleniumHW4.java
> +        driver.get("https://darksky.net/");
fixed

2021-09-30 00:41 UTC, julianoh7 commented on src/test/java/SeleniumHW4.java
> +        driver.get("https://darksky.net/");
thank you

2021-09-30 00:44 UTC, julianoh7 commented on src/test/java/SeleniumHW4.java
> +        String actualText = driver.findElement(By.xpath("//time[text()='June 7, 2021']")).getText();
still not sure about this one where to compare the format because I don't see month,day,year I think they can just post the date format in any way the publisher decides because I don't see a format in place. Hopefully we can go over it in class.

2021-09-30 00:45 UTC, merged